config/routes.rb
Foamer::Application.routes.draw do

  resources :calendars

  root :to => "static_pages#signin"
  
  get "/signin" => "static_pages#signin", :as => :signin
  get "/welcome" => "static_pages#welcome", :as => :welcome

  get "/home" => "events#home", :as => :home
  match "/refresh" => "events#refresh", :as => :refresh_events
  get "/got_nothing" => "events#got_nothing", :as => :got_nothing
  get "/event_review" => "events#event_review", :as => :event_review
  get "/travel_mode" => "events#travel_mode", :as => :travelmode

  resources :events
  resources :places
  resources :users

  get '/calendar_review' => 'calendars#calendar_review', :as => :calendar_review
  
  match '/auth/failure' => 'sessions#failure'
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/authenticate' => 'sessions#new', :as => :authenticate
  match '/auth/:provider/callback' => 'sessions#create'

  get "/home/:page" => "events#home"

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :end, :g_created, :g_updated, :google_id, :latitude, :location, :longitude, :start, :summary, :timezone, :description, :recurringEventId, :skip, :calendar_id
  geocoded_by :location
  after_validation :geocode, :if => :location_changed?
  belongs_to :calendar
  # validates_presence_of :location
  # validates_presence_of :location, :skip  
# if skip = true
end

  

app/controllers/events_controller.rb
# TODO: gotta handle situations where events from user's calendar doesn't have an address.

class EventsController < ApplicationController
  require 'google/api_client'
  require 'client_builder'
  
  before_filter :authenticate_user!
  

  def got_nothing
  end

  def event_review
    get_events
    event_check
  end

    def travel_mode
    end

  # root url
  def home

      if (cookies[:lat_lng])
        @lat_lng = cookies[:lat_lng].split("|")
        # See if we have a Current Location in Place, and update coordinates if so. Otherwise, create.
        if location = current_user.places.find_by_name("Current Location")
           location.update_attributes(:address => "#{@lat_lng[0]}, #{@lat_lng[1]}", 
                                      :latitude => @lat_lng[0], 
                                      :longitude => @lat_lng[1])
        else
          current_user.places.create(:name => "Current Location",
                                      :address => "#{@lat_lng[0]}, #{@lat_lng[1]}", 
                                      :latitude => @lat_lng[0], 
                                      :longitude => @lat_lng[1])
        end
      end

      # If no calendars for some reason, take the user to CalendarController#calendar_review
      if current_user.calendars.size == 0
        redirect_to calendar_review_path
      end

      # If no events found in our database, show got_nothing page where user can try refreshing from Google.
      if current_user.events.where("start >= ? AND events.skip = ?", Time.now.in_time_zone(current_user.timezone), false).size == 0
        redirect_to got_nothing_url
      else
        # TODO: Every time we load the page, we have a database hit to load the events. Decouple this from the view generation.
        @events = current_user.events.where("start >= ? AND events.skip = ?", Time.now.in_time_zone(current_user.timezone), false).order("start ASC")
        
        # set travel_mode to be used in forms to user's saved preference
        # TODO: set this once per session and not hit database every time
        if current_user.travel_mode
          session[:travel_mode] = current_user.travel_mode
        else 
          session[:travel_mode] = "DRIVING"
        end
        # Get list of user's saved places, not meaningfully used yet
        @places = current_user.places
      end
  end


  # GET /events
  # GET /events.json
  def index
    @events = current_user.events.where("start >= ?", Date.today)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.js { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  def refresh
    get_events
    redirect_to event_review_path, :notice => 'Events refreshed from Google Calendar!'
  end


  private

      # TODO: refactor this into general purpose API query method where we can pass which google API/resources/params
    def get_events

      # Delete all current events, we're going to query google and grab a fresh list
      # TODO: Instead of destroying all, compare events at Google to what we grabbed and if changed, update
      current_user.calendars.map {|x| x.events.destroy_all}

      today_start = DateTime.now.in_time_zone(current_user.timezone).to_datetime.at_beginning_of_day.rfc3339
      today_end = DateTime.now.in_time_zone(current_user.timezone).to_datetime.end_of_day.rfc3339

      current_user.calendars.where("active = ?", true).each do |calendar|

        client =  ClientBuilder.get_client(current_user)
        service = client.discovered_api('calendar', 'v3')
        resource = client.execute(:api_method => service.events.list, 
                                  :parameters => {
                                    'calendarId' => calendar.google_id, 
                                    'orderBy' => 'startTime', 
                                    'singleEvents' => 'true',
                                    # 'timeMin' => '2012-11-05T00:00:00-06:00',
                                    # 'timeMax' => '2012-11-05T23:59:59-06:00'
                                    'timeMin' => today_start,
                                    'timeMax' => today_end
                                    }) 
        @api_data = resource.data
      
        resource.data.items.each do |item|
          event_hash = Hash.new
          event_hash[:summary] = item["summary"]
          event_hash[:google_id] = item["id"]
          event_hash[:g_created] = item["created"]
          event_hash[:g_updated] = item["updated"]
          # event_hash[:timezone] = timezone
          if item["recurringEventId"].present?
            event_hash[:recurringEventId] = item["recurringEventId"]
          end
          if item["location"].present?
            event_hash[:location] = item["location"]
          end
          if item["description"].present?
            event_hash[:description] = item["description"]
          end
          if item["start"]["dateTime"].present?
            event_hash[:start] = item["start"]["dateTime"]
            event_hash[:end] = item["end"]["dateTime"]
          else
            event_hash[:start] = item["start"]["date"]
            event_hash[:end] = item["end"]["date"]
          end
          event_hash[:skip] = false
          event = calendar.events.new(event_hash)
          event.save 
        end

      end 
      # TODO: we might add more of the same events to the database. Need a check.
      @events_today = current_user.events.where("start >= ?", Date.today).order("start ASC")
    end

    def event_check
      # Cycle through events and see if lat/long are missing, which means we don't have an address.
      if @events_today.where(:skip => false).size == 0
        redirect_to got_nothing_url
      else
        @events_no_address = []
        @events_today.each do |event|
          if event.latitude.nil? || event.longitude.nil?
            @events_no_address.push(event)
          end
        end
      end
    end

 end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_calcroute_setup.erb
<script type="text/javascript">

	<% if params[:page].nil? %>
		// <%# TODO: Use latlng cookie instead of DB %>
	  var start = "<%= current_location.address %>";
  <% else %>
	  var start = "<%= @events[params[:page].to_i - 1][:location] %>";
  <% end %>
	  var end = "<%= @events[params[:page].to_i][:location] %>";
	  var arrive = <%= @events[params[:page].to_i][:start].to_f * 1000 %>;
</script>

app/views/events/_event_review_form.html.erb
<li>
	<div class="time"><%= event[:start].strftime("%l:%M%P") %></div>
  <div class="eventTitle"><%= event.summary %></div>
  <div class="buttons">
    <!-- <button class="geo-location" onclick="getGeoLocation();"></button> -->
    <!-- <img class="geo-locationimage" src="/assets/geolocation.png"> -->
		<%= form_for(event, :remote => true) do |f| %>
      <%= f.text_field :location, :placeholder => 'Add an Address', :class => 'submittable location' %>
      <div class="skipit"><a href="#">Skip This Trip</a></div>
	    <%= f.check_box :skip, :class => 'submittable' %> 
	    <%= f.label "Skip It" %>
		<% end %>
	</div><!--/buttons-->
</li>

app/views/events/_events.html.erb
<div class="agendaview">  
  <ul>
      <li>
      <% if params[:page].nil? %>
        <div class="time"><%= @events[0][:start].strftime("%l:%M%P") %></div>
        <div class="eventTitle"><%= @events[0][:summary] %></div>   
      <% else %>
        <div class="time"><%= @events[params[:page].to_i][:start].strftime("%l:%M%P") %></div>
        <div class="eventTitle"><%= @events[params[:page].to_i][:summary] %></div> 
      <% end %>
      </li>
  </ul>
</div><!--/agendaview-->
<!-- <div class="arrowbox"> -->
  <!-- <ul> -->
    <%# if params[:page].to_i >= 1 %>
      <!-- <li><a href="/home/<%#= params[:page].to_i - 1 %>"><img src="/assets/arrowleft.png"></a> -->
    <%# end %>
    <%# if params[:page].to_i + 1 <#= @events.length.to_i - 1 %>
        <!-- <li><a href="/home/<%#= params[:page].to_i + 1 %>"><img src="/assets/arrow.png"></a> -->
      <%# end %>
    <!-- </ul> -->
<!-- </div> --><!--/arrowbox-->
<div class="tofrom">
  <ul>
  <% if params[:page].nil? %>
    <li><span>from</span><br>Current Location</li>
  <% else %>
    <li><span>from</span><br><%= @events[params[:page].to_i - 1][:summary] %></li>
  <% end %>
    <li><span>to</span><br><%= @events[params[:page].to_i][:location] %></li>
  </ul>
</div><!--/tofrom-->

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :google_id %><br />
    <%= f.text_field :google_id %>
  </div>
  <div class="field">
    <%= f.label :g_created %><br />
    <%= f.text_field :g_created %>
  </div>
  <div class="field">
    <%= f.label :g_updated %><br />
    <%= f.text_field :g_updated %>
  </div>
  <div class="field">
    <%= f.label :summary %><br />
    <%= f.text_field :summary %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :start %><br />
    <%= f.datetime_select :start %>
  </div>
  <div class="field">
    <%= f.label :end %><br />
    <%= f.datetime_select :end %>
  </div>
  <div class="field">
    <%= f.label :timezone %><br />
    <%= f.text_field :timezone %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
      <%= f.label :calendar_id %><br />
      <%= f.text_field :calendar_id %>
    </div>
    <div class="field">
      <%= f.label :skip %><br />
      <%= f.text_field :skip %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_mapform.html.erb
<!-- <%# TODO: Allow From: to be current location, manual, or from saved place %>  -->

<script type="text/javascript">
  function setUserTravelMode() {
  $('input#travelMode_<%= session[:travel_mode] %>').attr('checked',true)
  .parents('form:first').submit();
  $('li#travelMode_<%= session[:travel_mode] %>').addClass('clickable');
  }
</script>


<div class="modes">
  <ul class="modes">
    <li>Your Ride</span></li>
    <li id="travelMode_TRANSIT"><img src="/assets/train.png"><a href="www.google.com"></a></li>
    <li id="travelMode_BICYCLING"><img src="/assets/bike.png"><a href="www.google.com"></a></li>
    <li id="travelMode_DRIVING"><img src="/assets/car.png"><a href="www.google.com"></a></li>
    <li id="travelMode_WALKING"><img src="/assets/walking.png"><a href="www.google.com"></a></li>
  </ul>
</div><!--/modes-->

<%= form_tag("/calcroute", :id => "routeForm", :class => "travel_mode_form", :onSubmit => "calcRoute();return false;") do %>
            
  <%#= label_tag(:routeStart, "Starting Place:") %>
  <%#= collection_select :routeStart, :place, current_user.places, :address, :name %>

  <!-- <%# TODO: We're not using waypoints. We have to build our own. Saving here as reference %> -->
  <%#= label_tag(:routeVia, "Waypoint: ") %>
  <%#= text_field_tag :routeVia, nil, :placeholder => "Addresses in between" %>
  <!-- <br><br> -->
  <%#= label_tag(:routeEnd, "Final Destination:") %>
  <%#= text_field_tag :routeEnd, nil, :placeholder => "Where you'll end the day..." %>
  <!-- Add in the arrive by time
  <%#= text_field_tag :routeEnd, @events.first.location %>   -->

  <%= radio_button_tag(:travelMode, "TRANSIT", false, :class => 'submittable') %>
  <%= radio_button_tag(:travelMode, "BICYCLING", false, :class => 'submittable') %>
  <%= radio_button_tag(:travelMode, "DRIVING", true, :class => 'submittable') %>
  <%= radio_button_tag(:travelMode, "WALKING", false, :class => 'submittable') %>

<% end %>

<script type="text/javascript">
  $(setUserTravelMode());
</script>

app/views/events/_submittable.js.erb
<script type="text/javascript">
  $(document).ready(
    $('.submittable').on('change', function() {
      $(this).parents('form:first').submit();
    })
  );

  $(document).ready(function(){
    $('.submittable').on('click', function() {
      $(".clickable").removeClass("clickable"); 
        console.log("workin on it");
        var buttonid = $(this).attr('id');
        $('#' + buttonid).addClass("clickable");         
      });
  });
</script>

app/views/events/_travel_mode_form.html.erb
<div class="modes">
  <ul class="modes">
    <li>Your Ride</span></li>
    <li id="user_travel_mode_transit"><img src="/assets/train.png"><a href="www.google.com"></a></li>
    <li id="user_travel_mode_bicycling"><img src="/assets/bike.png"><a href="www.google.com"></a></li>
    <li id="user_travel_mode_driving"><img src="/assets/car.png"><a href="www.google.com"></a></li>
    <li id="user_travel_mode_walking"><img src="/assets/walking.png"><a href="www.google.com"></a></li>
  </ul>
</div>

<%= form_for(@current_user, :html => { :class => "travel_mode_form" }, :remote => true) do |f| %>
  <div class="field">
    <%= f.radio_button("travel_mode", "TRANSIT", :class => 'submittable') %>
    <%= f.radio_button("travel_mode", "BICYCLING", :class => 'submittable') %>
    <%= f.radio_button("travel_mode", "DRIVING", :checked => true, :class => 'submittable clickable') %> 
    <%= f.radio_button("travel_mode", "WALKING", :class => 'submittable') %>
  </div>
<% end %>

app/views/events/event_review.html.erb
<%#TODO: use jQuery to check if addresses were actually entered  %>
<%#TODO: use Google Places API to get address/lat/long for name  %>

<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>

<!-- #TODO: This is a hack to capture latlng which is used immediately in the home view. Move this to welcome screen once we have them. -->
<script type="text/javascript">
  $(document).ready(function() {
      $(initialize());
  });
</script>

<div class="wrapper">
  <div class="content">
    <% if @events_no_address.size > 0 %>
      <div class="daynav">
        <img src="/assets/logo.png">
      </div><!-- /daynav-->
      <p class="introtext">We need some info and addresses to map your day.</p>
      <%= render 'travel_mode_form' %>  
      <p class="introtext">Enter event locations.</p>
      <div class="agendaview">
        <ul>
          <% @events_no_address.each do |event| %>
            <%= render 'event_review_form', :event => event %>
          <% end %>
        </ul>
      </div><!--/agendaview-->
    <% else %>
      <p><h2>You have addresses for your events. Thanks for that.</h2></p>
    <% end %>

    <p><h2><%= link_to "Map 'em!", home_path, :class => "zocial google" %></h2></p>           
  </div><!--/content-->
</div><!--/wrapper-->

<%= render 'submittable', :formats => [:js] %>

app/views/events/gimme_locations.html.erb
<div class="wrapper">
    
        
        <div class="hero-unit">

          <% @events_no_address.each do |event| %>
          <li class="edit_li"><%= event.summary %>
            <%= form_for(event, :remote => true) do |f| %>
              <div class="field">
                <%= f.text_field :location %>
              </div>
              <div class="field">
                <%= f.check_box :skip, :class => 'submittable' %> 
                <%= f.label "Skip this trip" %>
              </div>
              <div class="actions">
                <%= f.submit %>
              </div>
            <% end %></li>
          <% end %>

	          <h2>Entered your addresses? Let's Trip!<p>
              <%= link_to "Go", home_path, :class => "zocial google" %></p></h2>
		        
        </div>

</div><!--/wrapper-->

app/views/events/home.html.erb
<% content_for :page_scripts do %>
  <script type="text/javascript" src="http://maps.google.com/maps/api/js?key=AIzaSyBxxlbKadojUc5YHoKY2XiuO8d3RIZYths&sensor=false"></script>
  <%= render 'calcroute_setup', :format => [:js], :events => @events %>
  <style type="text/css">
  #mapContainer {
    height: 250px;
    width: 280px;
    /*border:5px solid #eaeaea;*/
  }

  </style>
<% end -%>

<div class="wrapper">
  

  <% if params[:page].to_i >= 1 %>
    <div class="arrowleft"><a href="/home/<%= params[:page].to_i - 1 %>"><img src="/assets/arrowleft.png"></a></div>
  <% end %>
    


  <div class="content">
    <div class="daynav">
      <img src="/assets/logo.png">
        <!-- <ul>
          <%#= link_to refresh_events_path do %>
            <li is "refreshbutton"><img src="/assets/refresh.png" id="refresh"></li> 
          <%# end %>
        </ul> -->
    </div><!--/daynav-->
    <div class="progress"></div>
    <%= render 'events', :events => @events %>
    </br>
    <%= render 'mapform' %>
    <br>
    <div class="map" id="mapContainer"></div>
    <div id="directionsPanel"></div>
  </div><!--/content-->
    <% if params[:page].to_i + 1 <= @events.length.to_i - 1 %>
        <div class="arrowright"><a href="/home/<%= params[:page].to_i + 1 %>"><img src="/assets/arrow.png"></a></div>
      <% end %>
</div><!--/wrapper-->
<%= render 'submittable', :formats => [:js] %>

<%#= debug event %>
<%#= binding.pry %>
<%#= debug @api_data %>
<%#= debug current_user.timezone if current_user %>
<%#= debug params[:page] %>
<%# binding.pry %>
<%#= debug session %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Google_ID</th>
    <th>G created</th>
    <th>G updated</th>
    <th>Summary</th>
    <th>Location</th>
    <th>Start</th>
    <th>End</th>
    <th>Timezone</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Calendar</th>
    <th>Skipped?</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.id %></td>
    <td><%= event.google_id %></td>
    <td><%= event.g_created %></td>
    <td><%= event.g_updated %></td>
    <td><%= event.summary %></td>
    <td><%= event.location %></td>
    <td><%= event.start %></td>
    <td><%= event.end %></td>
    <td><%= event.timezone %></td>
    <td><%= event.latitude %></td>
    <td><%= event.longitude %></td>
    <td><%= event.calendar_id %></td>
    <td><%= event.skip %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Google:</b>
  <%= @event.google_id %>
</p>

<p>
  <b>G created:</b>
  <%= @event.g_created %>
</p>

<p>
  <b>G updated:</b>
  <%= @event.g_updated %>
</p>

<p>
  <b>Summary:</b>
  <%= @event.summary %>
</p>

<p>
  <b>Location:</b>
  <%= @event.location %>
</p>

<p>
  <b>Start:</b>
  <%= @event.start %>
</p>

<p>
  <b>End:</b>
  <%= @event.end %>
</p>

<p>
  <b>Timezone:</b>
  <%= @event.timezone %>
</p>

<p>
  <b>Latitude:</b>
  <%= @event.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @event.longitude %>
</p>

<p>
  <b>Calendar:</b>
  <%= @event.calendar_id %>
</p>
<p>
  <b>Skipped:</b>
  <%= @event.skip %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/events/travel_mode.html.erb
<div class="wrapper">
  <div class="hero-unit">
    <h2>What's your default mode of travel?</h2>
    <h2>(You can change your travel mode for each event)</h2>
    <h2><%= render 'travel_mode_form' %></h2>
    <h2><%= link_to "Back to Maps!", home_path, :class => "zocial google" %></h2> 
  </div><!--/hero-unit-->
</div><!--/wrapper-->

app/views/events/update.js.erb
// <% #TODO: Placeholder for jQuery action to trigger after checkbox %>
// we could highlight the checkbox to show it's been clicked:
$('#event').css("color","yellow");

// or add the updated thing to a list:
$('#events').prepend('<%=escape_javascript render(@event) %>');