config/routes.rb
Foamer::Application.routes.draw do

  resources :calendars

  root :to => "static_pages#signin"
  
  get "/signin" => "static_pages#signin", :as => :signin
  get "/welcome" => "static_pages#welcome", :as => :welcome

  get "/home" => "events#home", :as => :home
  match "/refresh" => "events#refresh", :as => :refresh_events
  get "/got_nothing" => "events#got_nothing", :as => :got_nothing
  get "/event_review" => "events#event_review", :as => :event_review
  get "/travel_mode" => "events#travel_mode", :as => :travelmode

  resources :events
  resources :places
  resources :users

  get '/calendar_review' => 'calendars#calendar_review', :as => :calendar_review
  
  match '/auth/failure' => 'sessions#failure'
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/authenticate' => 'sessions#new', :as => :authenticate
  match '/auth/:provider/callback' => 'sessions#create'

  get "/home/:page" => "events#home"

end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
  attr_accessible :access_role, :active, :background_color, :color_id, :description, :etag, :foreground_color, :google_id, :kind, :selected, :summary, :time_zone, :user_id
  has_many :events
  belongs_to :user
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  require 'google/api_client'
  require 'client_builder'

  helper_method :get_user_timezone
  helper_method :get_calendars

  # TODO: some reason this doesn't work in this controller
  before_filter :authenticate_user!

  def calendar_review
    if current_user.calendars.size == 0
      get_calendars
    end
    @calendars = current_user.calendars
  end

  # GET /calendars
  # GET /calendars.json
  def index
    @calendars = Calendar.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @calendars }
    end
  end

  # GET /calendars/1
  # GET /calendars/1.json
  def show
    @calendar = Calendar.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.js { render json: @calendar }
    end
  end

  # GET /calendars/new
  # GET /calendars/new.json
  def new
    @calendar = Calendar.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @calendar }
    end
  end

  # GET /calendars/1/edit
  def edit
    @calendar = Calendar.find(params[:id])
  end

  # POST /calendars
  # POST /calendars.json
  def create
    @calendar = Calendar.new(params[:calendar])

    respond_to do |format|
      if @calendar.save
        format.html { redirect_to @calendar, notice: 'Calendar was successfully created.' }
        format.json { render json: @calendar, status: :created, location: @calendar }
      else
        format.html { render action: "new" }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /calendars/1
  # PUT /calendars/1.json
  def update
    @calendar = Calendar.find(params[:id])

    respond_to do |format|
      if @calendar.update_attributes(params[:calendar])
        format.html { redirect_to @calendar, notice: 'Calendar was successfully updated.' }
        format.js { head :no_content }
      else
        format.html { render action: "edit" }
        format.js { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendars/1
  # DELETE /calendars/1.json
  def destroy
    @calendar = Calendar.find(params[:id])
    @calendar.destroy

    respond_to do |format|
      format.html { redirect_to calendars_url }
      format.json { head :no_content }
    end
  end

    private
    
        def get_user_timezone
          client =  ClientBuilder.get_client(current_user)
          service = client.discovered_api('calendar', 'v3')
          resource = client.execute(:api_method => service.calendars.get, 
                                    :parameters => {
                                      'calendarId' => 'primary', 
                                      }) 
          current_user.timezone = resource.data["timeZone"]
          current_user.save
        end

        def get_calendars
          # delete any existing calendars (for when we refresh)
          current_user.calendars.destroy_all

          # Get the user's timezone from their primary Google Calendar.
          # Supposedly you can pull the user timezone when you first authorize via Oauth2,
          # but the response doesn't actually provide the timezone, despite what the docs
          # say here: https://developers.google.com/accounts/docs/OAuth2Login#userinfocall
          if !current_user.timezone
              get_user_timezone
          end

          client =  ClientBuilder.get_client(current_user)
          service = client.discovered_api('calendar', 'v3')
          resource = client.execute(:api_method => service.calendar_list.list)
          @all_calendars = resource.data 

          resource.data.items.each do |item|
            calendar_hash = Hash.new
            calendar_hash[:kind] = item["kind"]
            calendar_hash[:google_id] = item["id"]
            calendar_hash[:etag] = item["etag"]
            calendar_hash[:summary] = item["summary"]
            if calendar_hash[:description]
              calendar_hash[:description] = item["description"]
            end
            calendar_hash[:time_zone] = item["time_zone"]
            calendar_hash[:color_id] = item["color_id"]
            calendar_hash[:background_color] = item["background_color"]
            calendar_hash[:foreground_color] = item["foreground_color"]
            calendar_hash[:selected] = item["selected"]
            calendar_hash[:access_role] = item["access_role"]
            # calendar_hash[:active] = item["active"]

            calendar = current_user.calendars.new(calendar_hash)
            calendar.save
          end

    end

end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/_form.html.erb
<%= form_for(@calendar) do |f| %>
  <% if @calendar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@calendar.errors.count, "error") %> prohibited this calendar from being saved:</h2>

      <ul>
      <% @calendar.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calendars/calendar_review.html.erb
<div class="wrapper">
  <div class="hero-unit">
    <h2>We've found these calendars: </h2>
    <ul>
      <% @calendars.each do |calendar| %>
        <li><a style="color: <%= calendar.foreground_color %>; background-color: <%= calendar.background_color %>"><%= calendar.summary %></a>
        <%= form_for(calendar, :remote => true) do |f| %>
          <div class="field">
            <%= f.check_box :active, :class => 'submittable' %> 
            <%#= f.label "Use calendar" %>
          </div>
          <!-- <div class="actions">
            <%#= f.submit %>
          </div> -->
        <% end %></li>
      <% end %>
    </ul>
    <h2>Let's get your events!<p>
      <%= link_to "Next", event_review_path, :class => "zocial google" %></p></h2>
      
  </div>

</div><!--/wrapper-->

<script type="text/javascript">
  $(document).ready(function(){
    $('.submittable').on('click', function() {
          $(".clickable").removeClass("clickable"); 
            console.log("workin on it");
            var buttonid = $(this).attr('id');
            $('#' + buttonid).addClass("clickable");         
          });
  });
</script>

app/views/calendars/edit.html.erb
<h1>Editing calendar</h1>

<%= render 'form' %>

<%= link_to 'Show', @calendar %> |
<%= link_to 'Back', calendars_path %>

app/views/calendars/index.html.erb
<h1>Listing calendars</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @calendars.each do |calendar| %>
  <tr>
    <td><%= link_to 'Show', calendar %></td>
    <td><%= link_to 'Edit', edit_calendar_path(calendar) %></td>
    <td><%= link_to 'Destroy', calendar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Calendar', new_calendar_path %>

app/views/calendars/new.html.erb
<h1>New calendar</h1>

<%= render 'form' %>

<%= link_to 'Back', calendars_path %>

app/views/calendars/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_calendar_path(@calendar) %> |
<%= link_to 'Back', calendars_path %>