config/routes.rb
Foamer::Application.routes.draw do

  resources :calendars

  root :to => "static_pages#signin"
  
  get "/signin" => "static_pages#signin", :as => :signin
  get "/welcome" => "static_pages#welcome", :as => :welcome

  get "/home" => "events#home", :as => :home
  match "/refresh" => "events#refresh", :as => :refresh_events
  get "/got_nothing" => "events#got_nothing", :as => :got_nothing
  get "/event_review" => "events#event_review", :as => :event_review
  get "/travel_mode" => "events#travel_mode", :as => :travelmode

  resources :events
  resources :places
  resources :users

  get '/calendar_review' => 'calendars#calendar_review', :as => :calendar_review
  
  match '/auth/failure' => 'sessions#failure'
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/authenticate' => 'sessions#new', :as => :authenticate
  match '/auth/:provider/callback' => 'sessions#create'

  get "/home/:page" => "events#home"

end

app/models/place.rb
class Place < ActiveRecord::Base
  attr_accessible :name, :address, :user_id, :latitude, :longitude 
  geocoded_by :address
  after_validation :geocode 
  belongs_to :user

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  # GET /places
  # GET /places.json
  def index
    @places = current_user.places

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @places }
    end
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @place = Place.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @place }
    end
  end

  # GET /places/new
  # GET /places/new.json
  def new
    @place = Place.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @place }
    end
  end

  # GET /places/1/edit
  def edit
    @place = Place.find(params[:id])
  end

  # POST /places
  # POST /places.json
  def create
    @place = current_user.places.new(params[:place])

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render json: @place, status: :created, location: @place }
      else
        format.html { render action: "new" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /places/1
  # PUT /places/1.json
  def update
    @place = Place.find(params[:id])

    respond_to do |format|
      if @place.update_attributes(params[:place])
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place = Place.find(params[:id])
    @place.destroy

    respond_to do |format|
      format.html { redirect_to places_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>

   <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>

   <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<h1>Listing places</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @places.each do |place| %>
  <tr>
    <td><%= place.name %></td>
    <td><%= place.address %></td>
    <td><%= place.latitude %></td>
    <td><%= place.longitude %></td>
    <td><%= place.user.name %></td>
    <td><%= link_to 'Show', place %></td>
    <td><%= link_to 'Edit', edit_place_path(place) %></td>
    <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @place.name %>
</p>

<p>
  <b>Address:</b>
  <%= @place.address %>
</p>

<p>
  <b>Latitude:</b>
  <%= @place.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @place.longitude %>
</p>


<p>
  <b>User:</b>
  <%= @place.user.name %>
</p>


<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>